In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [8]:
#Problema do XOR:

#Dados de treinamento para o problema XOR:
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([[0], [1], [1], [0]])

#Construindo o modelo com função Sigmoid e ReLu:
model_xor = Sequential([Dense(2, input_dim=2, activation='sigmoid'), Dense(1, activation='relu')]) # Camada intermediária com 2 neurônios e camada de saída com 1 neurônio

#Compilando o modelo:
model_xor.compile(optimizer='adam', loss='mean_squared_error')

#Treinando o modelo:
model_xor.fit(X_xor, y_xor, epochs=5000, verbose=0) #5000 épocas

#Testando o modelo:
outputs_xor = model_xor.predict(X_xor)
print("Resultados para o problema XOR:")
print(np.round(outputs_xor, decimals=4))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
Resultados para o problema XOR:
[[0.0023]
 [0.9969]
 [0.997 ]
 [0.0041]]


In [3]:
#Problema Matriz Identidade:

def mapeamento_identidade(dimensao_matriz_identidade):

  # Matriz Identidade:
  input_size = dimensao_matriz_identidade
  hidden_size = int(np.log2(input_size))  # Quantidade de Neurônios intermediária
  output_size = input_size
  X = np.eye(input_size)

  # Construindo o modelo:
  model_autoencoder = Sequential([
      Dense(hidden_size, input_dim=input_size, activation='sigmoid'),  # Camada oculta - Função sigmoid
      Dense(output_size, activation='sigmoid')  # Camada de saída - Função sigmoid
  ])

  # Compilando o modelo:
  model_autoencoder.compile(optimizer='adam', loss='mean_squared_error')

  # Treinando o modelo
  model_autoencoder.fit(X, X, epochs=5000, verbose=0) #5000 épocas

  # Testando o modelo
  outputs = model_autoencoder.predict(X)
  print(f"\nMapeamento identidade {input_size}x{output_size} concluído.")
  return outputs

In [4]:
matriz = mapeamento_identidade(8) #Matriz 8x8:
print(np.round(matriz,3))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

Mapeamento identidade 8x8 concluído.
[[0.13  0.075 0.081 0.128 0.131 0.062 0.134 0.094]
 [0.114 0.771 0.093 0.178 0.023 0.001 0.138 0.133]
 [0.165 0.155 0.803 0.122 0.282 0.03  0.181 0.015]
 [0.123 0.13  0.041 0.141 0.075 0.038 0.128 0.154]
 [0.117 0.004 0.1   0.065 0.595 0.112 0.113 0.012]
 [0.151 0.005 0.033 0.117 0.265 0.796 0.132 0.192]
 [0.125 0.095 0.083 0.124 0.128 0.033 0.131 0.076]
 [0.104 0.09  0.001 0.176 0.019 0.134 0.101 0.723]]


In [5]:
matriz_2 = mapeamento_identidade(15) #Matriz 15x15:
print(np.round(matriz_2,3))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

Mapeamento identidade 15x15 concluído.
[[0.054 0.048 0.046 0.048 0.054 0.072 0.1   0.055 0.056 0.059 0.08  0.055
  0.046 0.066 0.049]
 [0.047 0.044 0.041 0.055 0.047 0.059 0.087 0.053 0.051 0.055 0.056 0.048
  0.043 0.073 0.046]
 [0.053 0.048 0.046 0.052 0.053 0.071 0.094 0.057 0.056 0.059 0.074 0.055
  0.047 0.074 0.05 ]
 [0.104 0.119 0.105 0.609 0.091 0.064 0.25  0.144 0.105 0.167 0.027 0.084
  0.122 0.218 0.135]
 [0.053 0.046 0.046 0.035 0.055 0.081 0.087 0.055 0.055 0.054 0.1   0.058
  0.045 0.067 0.047]
 [0.078 0.065 0.072 0.023 0.088 0.19  0.069 0.088 0.078 0.062 0.292 0.112
  0.065 0.121 0.063]
 [0.1   0.087 0.092 0.188 0.094 0.076 0.401 0.065 0.091 0.131 0.088 0.07
  0.08  0.035 0.093]
 [0.054 0.055 0.05  0.077 0.055 0.084 0.053 0.089 0.06  0.06  0.064 0.068
  0.057 0.193 0.058]
 [0.05  0.046 0.043 0.047 0.05  0.07  0.078 0.058 0.053 0.055 0.071 0.054
  0.045 0.082 0.047]
 [0.056 0.053 0.049 0.104 0.053 0.053 0.144 0.057 0.058 0.073 0.046 